### ISSUE TITLE
error while saving project

### ISSUE THREAD

**Issue by h20003** [capesean/codegenerator3#1]
Hello,

I am getting error while saving project. 
![codegen3 error](https://github.com/capesean/codegenerator3/assets/1585495/6a02ba4a-29cd-4cc2-b624-c9d5dd665f7d)

**Comment by capesean** [comment]
Hi @h20003. Thanks for logging the error! I've just uploaded a fix.

**Comment by h20003** [comment]
thanks, it is working now.
